name: Publish
on: push
permissions:
  contents: write
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-date
        run: echo "DATE=$(date '+%b %d, %Y')" >> $GITHUB_OUTPUT
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf
            ./fonts/*.otf
      - uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: "*.pdf"
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Resume (${{ steps.get-date.outputs.DATE }})
          body: |
            This resume is published on ${{ steps.get-date.outputs.DATE }}
          files: "*.pdf"
